#define IDH_FOLDERMENUS_ENABLE               1
#define IDH_APPROACHITEMS_ENABLE             2
#define IDH_SHOWITEMS                        3
#define IDH_AUTORUN                          4
#define IDH_INITIALMENU                      5
#define IDH_CHILDMENU                        6
#define IDH_SCROLLING                        7
#define IDH_WHEELSCROLLS                     8
#define IDH_PAGESCROLLS                      9
#define IDH_OKBUTTON                        10
#define IDH_CANCELBUTTON                    11
#define IDH_HELPBUTTON                      12
#define IDH_HIDDENFILES                     13
#define IDH_BROWSEFORFOLDERS                14
#define IDH_ZIPSAREFOLDERS                  15
#define IDH_MAXWIDTH                        16
#define IDH_MAXWIDTHPIXELS                  17
#define IDH_MAXWIDTHPERCENT                 18
#define IDH_SORTALPHABEICALLY               19
#define IDH_FOLDERSPRECEDEFILES             20
#define IDH_SINGLEFILESDOUBLEFOLDERS        21
#define IDH_SINGLEFILESSINGLEFOLDERS        22
#define IDH_DOUBLEFILESDOUBLEFOLDERS        23
#define IDH_FEEDBACK                        24
#define IDH_HOMEPAGE                        25