//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by w:\KOApproach\_proj90\Approach\ApproachWithStrings.rc
//
#define IDR_TRAYMENU                    100
#define IDD_O                           110
#define IDD_O_FEAT                      111
#define IDD_O_CNTS                      112
#define IDD_O_MNTC                      113
#define IDD_O_REG                       114
#define IDD_O_RGOK                      114
#define IDD_O_RGNO                      115
#define IDD_O_MNSC                      117
#define IDD_O_ABT                       118
#define IDD_APCHITMS                    120
#define IDD_ACTN                        130
#define IDB_ARROW_N                     200
#define IDB_ARROW_S                     201
#define IDB_DARROW_N                    202
#define IDB_DARROW_S                    203
#define IDB_UARROW_N                    204
#define IDB_UARROW_S                    205
#define IDB_FT_FLDMENUS                 206
#define IDB_FT_APCHITEMS                207
#define IDB_FT_TBARMENUS                208
#define IDI_APPROACH                    209
#define IDI_ACTIVATION                  210
#define IDI_RUNRECENT                   211
#define IDC_ACTN_BTN1                   1001
#define IDC_ACTN_BTN2                   1002
#define IDS_ACTN_DS_CONN                1000
#define IDS_ACTN_DS_CONNERR             1000
#define IDS_ACTN_DS_GNRCERR             1000
#define IDS_ACTN_DS_HWIDERR             1000
#define IDS_ACTN_DS_KEYACCS             1000
#define IDS_ACTN_DS_LMTEXCD             1000
#define IDS_ACTN_DS_RSTR                1000
#define IDS_ACTN_DS_SRNMERR             1000
#define IDS_ACTN_DS_SUCC                1000
#define IDL_ACTN_ICON                   1003
#define IDS_ACTN_ST_CONN                1000
#define IDS_ACTN_ST_FAIL                1000
#define IDS_ACTN_ST_RSTR                1000
#define IDS_ACTN_ST_SUCC                1000
#define IDL_ACTN_STATUS                 1004
#define IDM_ACTN_BTNSIZE                1000
#define IDM_ACTN_BTNSPACING             1000
#define IDM_ACTN_BTNVERTPOS             1000
#define IDS_APCHITEMS_ITEMPROC_QUIT     1000
#define IDS_APCHITEMS_ITEMPROC_REVEAL   1000
#define IDS_APCHITEMS_ITEMPROC_SYS      1000
#define IDS_APCHITEMS_ITEMPROC          1000
#define IDS_APCHITEMS_ITEMRUN           1000
#define IDC_APCHITMS_ADD                1029
#define IDL_APCHITMS_ALL                1034
#define IDC_APCHITMS_ALL                1036
#define IDC_APCHITMS_BRW                1030
#define IDL_APCHITMS_CUR                1035
#define IDC_APCHITMS_CUR                1037
#define IDC_APCHITMS_DOWN               1031
#define IDC_APCHITMS_RMV                1032
#define IDC_APCHITMS_UP                 1033
#define IDM_APCHITMS_CANCEL             1000
#define IDM_APCHITMS_OK                 1000
#define IDS_EXCEPT_EMPTY                1000
#define IDS_EXCEPT_GENERIC              1000
#define IDS_EXCEPT_UNAVAILABLE          1000
#define IDS_GLBL_CMD_CANCEL             1000
#define IDS_GLBL_CMD_HELP               1000
#define IDS_GLBL_CMD_NO                 1000
#define IDS_GLBL_CMD_OK                 1000
#define IDS_GLBL_CMD_RETRY              1000
#define IDS_GLBL_CMD_YES                1000
#define IDM_GLBL_LANGRTL                1000
#define IDM_GLBL_MILLISECFMT            1000
#define IDS_GLBL_ALWAYS                 1000
#define IDS_GLBL_ERROR                  1000
#define IDS_GLBL_MILLISEC               1000
#define IDS_GLBL_NEVER                  1000
#define IDS_GLBL_USESYSSETTING          1000
#define IDS_GLBL_WARNING                1000
#define IDS_KEYDLG_FILTER               1000
#define IDS_KEYDLG_TITLE                1000
#define IDC_O_ABT_APPCOPY               1001
#define IDC_O_ABT_APPICON               1002
#define IDC_O_ABT_APPNAME               1003
#define IDC_O_ABT_APPVER                1004
#define IDC_O_ABT_FEEDBACK              1005
#define IDC_O_ABT_HOMEPAGE              1006
#define IDC_O_ABT_HORRULE               1007
#define IDC_O_ABT_LICENSE               1008
#define IDC_O_ABT_THXCAPTION            1009
#define IDC_O_ABT_THXLIST               1010
#define IDM_O_ABT_NUMTHANKSLINES        1000
#define IDS_O_ABT_THX1                  1000
#define IDS_O_ABT_THX2                  1000
#define IDS_O_ABT_THX3                  1000
#define IDS_O_ABT_THX4                  1000
#define IDS_O_ABT_VERSION               1000
#define IDS_O_CNTS_BROWSEFLD_0NEWWND    1000
#define IDS_O_CNTS_BROWSEFLD_1SAMEWND   1000
#define IDL_O_CNTS_BROWSEFLD            1001
#define IDC_O_CNTS_BROWSEFLD            1002
#define IDL_O_CNTS_CAT_ICONS            1003
#define IDL_O_CNTS_CAT_ITEMS            1004
#define IDL_O_CNTS_CAT_ORDER            1005
#define IDC_O_CNTS_FLDORD_0TOP          1007
#define IDC_O_CNTS_FLDORD_1BOTM         1008
#define IDC_O_CNTS_FLDORD_2MIX          1009
#define IDC_O_CNTS_HDNITMS_DIMICN       1006
#define IDL_O_CNTS_HDNITMS              1016
#define IDC_O_CNTS_HDNITMS              1017
#define IDC_O_CNTS_ICN_0GENERIC         1010
#define IDC_O_CNTS_ICN_1REGULAR         1011
#define IDC_O_CNTS_ICNOPTIMIZ           1012
#define IDC_O_CNTS_ICNOVERLAYS          1013
#define IDS_O_CNTS_MOUSEITEMCLK_0REG    1000
#define IDS_O_CNTS_MOUSEITEMCLK_1SGL    1000
#define IDS_O_CNTS_MOUSEITEMCLK_2DBL    1000
#define IDL_O_CNTS_MOUSEITEMCLK         1014
#define IDC_O_CNTS_MOUSEITEMCLK         1015
#define IDC_O_CNTS_SORTITEMS            1018
#define IDC_O_CNTS_SSFIS_0FOLDER        1019
#define IDC_O_CNTS_SSFIS_1FILE          1020
#define IDL_O_CNTS_SSFISWHAT            1021
#define IDC_O_CNTS_ZIPIS_0FOLDER        1022
#define IDC_O_CNTS_ZIPIS_1FILE          1023
#define IDL_O_CNTS_ZIPISWHAT            1024
#define IDL_O_FEAT_APCHITEMSDESC        1001
#define IDC_O_FEAT_APCHITEMSOPT         1002
#define IDC_O_FEAT_APCHITEMSTGL         1003
#define IDL_O_FEAT_APCHITEMSVIS         1004
#define IDL_O_FEAT_CAT_APCHITEMS        1005
#define IDL_O_FEAT_CAT_FLDMENUS         1006
#define IDL_O_FEAT_CAT_TTLBARMENUS      1007
#define IDC_O_FEAT_CURFLDAUTOSEL        1008
#define IDC_O_FEAT_CURFLDISFILE         1009
#define IDC_O_FEAT_DESKPOS_0TOP         1010
#define IDC_O_FEAT_DESKPOS_1BOTM        1011
#define IDL_O_FEAT_FLDMENUSDESC         1012
#define IDC_O_FEAT_FLDMENUSTGL          1013
#define IDL_O_FEAT_FLDMENUSVIS          1014
#define IDL_O_FEAT_FOLDERMENUS          1015
#define IDL_O_FEAT_INITDELAY            1016
#define IDC_O_FEAT_INITDELAY            1017
#define IDL_O_FEAT_INITDELAYVAL         1018
#define IDL_O_FEAT_TITLEBARMENUS        1019
#define IDL_O_FEAT_TTLBARMENUSDESC      1020
#define IDC_O_FEAT_TTLBARMENUSTGL       1021
#define IDL_O_FEAT_TTLBARMENUSVIS       1022
#define IDL_O_MNSC_CAT_MENUS            1000
#define IDL_O_MNSC_CAT_SCROLLING        1001
#define IDL_O_MNSC_CHILDDELAY           1002
#define IDC_O_MNSC_CHILDDELAY           1003
#define IDL_O_MNSC_CHILDDELAYVAL        1004
#define IDC_O_MNSC_DISPNUMTOSCROLL      1005
#define IDL_O_MNSC_MAXMNUWIDTH          1006
#define IDC_O_MNSC_MAXMNUWIDTH          1007
#define IDC_O_MNSC_MAXMNUWIDTHSPIN      1008
#define IDC_O_MNSC_MNUWIDTH_0PXL        1009
#define IDC_O_MNSC_MNUWIDTH_1PRC        1010
#define IDL_O_MNSC_PAGEITEMS            1011
#define IDL_O_MNSC_PAGESCROLLS          1012
#define IDC_O_MNSC_PAGESCROLLS          1013
#define IDC_O_MNSC_PAGESCROLLSSPIN      1014
#define IDL_O_MNSC_SCROLLARROWS         1015
#define IDL_O_MNSC_SCROLLDELAY          1016
#define IDC_O_MNSC_SCROLLDELAY          1017
#define IDL_O_MNSC_SCROLLDELAYVAL       1018
#define IDC_O_MNSC_SCROLLING            1019
#define IDC_O_MNSC_SCROLLPOS_0TOP       1020
#define IDC_O_MNSC_SCROLLPOS_1BOTM      1021
#define IDC_O_MNSC_SCROLLPOS_2ENDS      1022
#define IDL_O_MNSC_WHEELITEMS           1023
#define IDL_O_MNSC_WHEELSCROLLS         1024
#define IDC_O_MNSC_WHEELSCROLLS         1025
#define IDC_O_MNSC_WHEELSCROLLSSPIN     1026
#define IDL_O_MNTC_AUTORUN              1029
#define IDC_O_MNTC_AUTORUN              1004
#define IDL_O_MNTC_CAT_MNTC             1016
#define IDL_O_MNTC_CAT_PLUGINS          1020
#define IDC_O_MNTC_LOCALEINFO           1059
#define IDS_O_MNTC_MSG_RESTDEF          1000
#define IDS_O_MNTC_MSG_UPDNO            1000
#define IDS_O_MNTC_MSG_UPDYES           1000
#define IDC_O_MNTC_PLGNDSBL             1010
#define IDC_O_MNTC_PLGNENBL             1011
#define IDS_O_MNTC_PLGNLST_DISABLED     1000
#define IDS_O_MNTC_PLGNLST_LOADED       1000
#define IDS_O_MNTC_PLGNLST_NAME         1000
#define IDS_O_MNTC_PLGNLST_NOTLOADED    1000
#define IDS_O_MNTC_PLGNLST_STATUS       1000
#define IDS_O_MNTC_PLGNLST_STOPPING     1000
#define IDC_O_MNTC_PLGNLST              1101
#define IDL_O_MNTC_RESTDEF              1028
#define IDC_O_MNTC_RESTDEF              1108
#define IDS_O_MNTC_UILANG_MORE          1000
#define IDL_O_MNTC_UILANG               1027
#define IDC_O_MNTC_UILANG               1058
#define IDL_O_MNTC_UPDATE               1138
#define IDC_O_MNTC_UPDATEAUTO           1158
#define IDC_O_MNTC_UPDATE               1026
#define IDL_O_RGNO_ACTDESC1             1001
#define IDL_O_RGNO_ACTDESC2             1002
#define IDC_O_RGNO_ACTIVATE             1003
#define IDL_O_RGNO_CAT_ACTIVN           1004
#define IDL_O_RGNO_CAT_LIC              1005
#define IDL_O_RGNO_INETICN              1006
#define IDL_O_RGNO_INETREQD             1007
#define IDC_O_RGNO_KEYRESTORE           1008
#define IDC_O_RGNO_PURCHASE             1009
#define IDL_O_RGNO_SERNUM               1010
#define IDC_O_RGNO_SERNUM               1011
#define IDC_O_RGNO_SERNUMHIDE           1012
#define IDL_O_RGNO_UNREGICN             1013
#define IDL_O_RGOK_BACKUP               1001
#define IDC_O_RGOK_BACKUP               1002
#define IDL_O_RGOK_CAT_KEYBKP           1003
#define IDL_O_RGOK_CAT_USER             1004
#define IDL_O_RGOK_REGUSER              1005
#define IDC_O_RGOK_REGUSER              1006
#define IDC_OPTS_CANCEL                 1000
#define IDC_OPTS_HELP                   1001
#define IDC_OPTS_OK                     1000
#define IDC_OPTS_PROPPAGETREE           1002
#define IDM_OPTS_BUTTONSIZE             1000
#define IDM_OPTS_CATEGORIESWIDTH        1000
#define IDM_OPTS_CONTROLMARGIN          1000
#define IDS_WARNTXT_FEATURELOCKED       1000
#define IDS_WARNTXT_INVALIDKEY          1000
#define IDP_CXMN_TOAPPROACHITEMS        32000
#define IDP_MAIN_ENBL_FLDMNUS           32773
#define IDP_MAIN_ENBL_APCHITMS          32774
#define IDP_MAIN_ENBL_TTLBARMNUS        32775
#define IDP_MAIN_OPTIONS                32776
#define IDP_MAIN_HELP                   32777
#define IDP_MAIN_EXIT                   32778
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
